### ISSUE TITLE
Support native hypervisors

### ISSUE THREAD

**Issue by ferrarimarco** [netgroup/kubernetes-playground#144]
We're currently using Virtualbox and libvirt (on Linux only). We should start using native hypervisors, and keep Virtualbox as a fallback option. This should bring a number of benefits:

- Better performance (claim to verify).
- Better OS integration. On Windows you cannot use Virtualbox and Hyper-v at the same time, and if you enable Hyper-v support, you cannot run Virtualbox, and this might pose some limitations. For example, Docker on Windows needs Hyper-v, and if you need to use Virtualbox, you cannot run Docker containers.

Thoughts?

@StefanoSalsano @zvfvrv @simonezacca

**Comment by StefanoSalsano** [comment]
Hi @ferrarimarco IMO we are ok with the current situation: on linux we have a platform that can be used over KVM with the libvirt provider and so it can be used also for taking realistic performance measurements as needed for the kites project
I think that the solution using Virtualbox provider is a very useful tool for development and testing if you have a laptop with windows or MAC as main OS (which is my case... and I think it is a very common situation)
personally, I have no interest in improving the performance of k8s-playground when run over a windows or on a MAC laptop... I only need it to be good enough to support the development and testing phase with reasonable performance (which we have solved with the cleanup and mount-shared provisioner)
of course is you are interested in improving the performance under windows/MAC I am not against it :-) I'm just saying that this is not needed for the kites project

**Comment by ferrarimarco** [comment]
There might be troubles with macOS, because Vagrant support for [xhyve](https://github.com/machyve/xhyve) is fairly limited AFAIK.

I still see the value in switching to Hyper-V on Windows.

**Comment by ferrarimarco** [comment]
Note to self: libvirt supports HyperV.
